### ISSUE TITLE
Port ranges for drop rules (Feature Request)

### ISSUE THREAD

**Issue by problematiq** [arkime/arkime#1841]
Currently to specify more than a single port for a drop rule it requires writing a rule per port.

```
---
version: 1
rules:
  - name: "Drop HTTP and HTTPS because I'm crazy"
    when: "fieldSet"
    fields:
      port:
      - 80
    ops:
      _maxPacketsToSave: 10
  - name: "Drop HTTP and HTTPS because I'm crazy pt 2"
    when: "fieldSet"
    fields:
      port:
      - 443
    ops:
      _maxPacketsToSave: 10
```
It would be nice to be able to use port ranges and multiple ports.
The port range delimiter could be `-` and/or `:` to fit firewall standards.
Multiple ports should be separated via comma `,`.
```
---
version: 1
rules:
  - name: "Drop HTTP and HTTPS because I'm crazy"
    when: "fieldSet"
    fields:
      ip:
      - 172.25.50.251
      port:
      - 80,443
    ops:
      _maxPacketsToSave: 10
  - name: "Drop ftp because I'm crazy"
    when: "fieldSet"
    fields:
      port:
      - 20-21
    ops:
      _maxPacketsToSave: 10
  - name: "Drop ftp because I'm crazy Alternative"
    when: "fieldSet"
    fields:
      port:
      - 20:21
    ops:
      _maxPacketsToSave: 10
```
