### ISSUE TITLE
Viewer does not work with S3 files from LocalStack

### ISSUE THREAD

**Issue by cpockrandt** [arkime/arkime#2838]
**Describe the bug**

Arkime viewer does not work when storing pcaps in s3 storage and using providers such as MinIO or LocalStack. It seems that they do not allow a leading forward slash in the key.

**Elasticsearch version**:

2.11.1

**Arkime/Moloch version**:

5.0.2

**OS name and version**:

Kubernetes

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

From source (release tar ball)

**Provide logs, stack traces and steps to reproduce**:

We got it to work with this patch - not sure whether this is the smartest way to go or whether it should be fixed in the capture process.

```diff
+---
+ viewer/schemes.js | 2 +-
+ 1 file changed, 1 insertion(+), 1 deletion(-)
+
+diff --git a/viewer/schemes.js b/viewer/schemes.js
+index cd8ab30..9a0976d 100644
+--- a/viewer/schemes.js
++++ b/viewer/schemes.js
+@@ -116,7 +116,7 @@ async function getBlockS3HTTP (info, pos) {
+ 
+       const params = {
+         Bucket: info.extra.bucket,
+-        Key: info.extra.path,
++        Key: info.extra.path.replace(/^\//, ''),
+         Range: `bytes=${blockStart}-${blockStart + blockSize}`
+       };
+ 
+-- 
+2.25.1
+
```

**Comment by awick** [comment]
* what version of minio? (I haven't noticed an issue before)
* can you give an example url that you are using with capture
* what are you seeing in info.extra.path?

**Comment by cpockrandt** [comment]
> what version of minio? (I haven't noticed an issue before)

We couldn't get MinIO running, currently we have a setup with LocalStack (https://www.localstack.cloud/). We encountered the same issue with the S3 storage provider in our on-prem cloud (for which I don't know the provider or any details).

```yaml
services:
  localstack:
    container_name: arkime-capture-s3-test-s3
    hostname: localstack.cloud
    image: localstack/localstack:3.0.2
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LOCALSTACK_HOST=localstack.cloud:4566
      - SERVICES=s3
```

> can you give an example url that you are using with capture

```ini
// /opt/arkime/etc/config.ini
[default]
// ...

### S3 Settings
s3Host=localstack.cloud:4566
s3Bucket=bucketname
s3PathAccessStyle=1
s3Region=us-east-1
s3AccessKeyId=test
s3SecretAccessKey=test
s3UseHttp=1
```

```
/opt/arkime/bin/capture -r s3http://localstack.cloud:4566/bucketname/m57.pcap
```

> what are you seeing in info.extra.path?

```js
      const params = {
// info.extra.path is '/' + info.extra.bucket + info.extra.path
// '/bucketname/m57.pcap', but only 'bucketname/m57.pcap' works for us (without leading slash)
        Bucket: info.extra.bucket, 
        Key: info.extra.path, 
        Range: `bytes=${blockStart}-${blockStart + blockSize}`
      };
```
