### ISSUE TITLE
Arkime Docker install

### ISSUE THREAD

**Issue by zijundidu** [arkime/arkime#3019]
Hey, I'm trying to install with 5.5.0 docker and unfortunately there is no full deployment documentation to support me in installing. I have an ES8.8.1 cluster but don't know how to initialize a container after the docker image is created

If I can, I'll provide a screenshot of the error

**Comment by zijundidu** [comment]
By the way, my OS version is Debian 10 and currently only see the version supported by Debian 12

**Comment by awick** [comment]
These two links might help http://arkime.com/questions and http://arkime.com/docker

**Comment by zijundidu** [comment]
I confirm that I've read all the official documentation, including these two：
 http://arkime.com/questions and http://arkime.com/docker
 
Unfortunately, the documentation didn't help me build an Arkime Container from scratch. Let me briefly talk about my operation and the problems I encountered.
 
First, I have ES-8.8.1 cluster, health and green: 
![img_v3_02gp_86cb1b42-a701-4489-bb35-de375592f7bg](https://github.com/user-attachments/assets/9cc0ea18-3326-437e-a936-0fae97d49571)

I downloaded the official image: ghcr.io/arkime/arkime/arkime:v5-latest
![img_v3_02gp_ed415d6b-57aa-4195-876b-8de771d272fg](https://github.com/user-attachments/assets/ee668f3f-db92-4242-b69d-613823c459e2)

Then I looked at the documentation：http://arkime.com/docker  ,and configured docker-compose.yaml
```
version: '3'

services:

  capture:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    network_mode: "host"
    command: /opt/arkime/bin/docker.sh capture --update-geo
    volumes:
      - /home/wzj/arkime/pcap:/opt/arkime/raw
      - /home/wzj/arkime/etc:/opt/arkime/etc
    restart: always
    container_name: arkime-capture
  viewer:
    image: ghcr.io/arkime/arkime/arkime:v5-latest
    network_mode: "host"
    command: /opt/arkime/bin/docker.sh viewer
    volumes:
      - /home/wzj/arkime/pcap:/opt/arkime/raw
      - /home/wzj/arkime/etc:/opt/arkime/etc
    restart: always
    container_name: arkime-viewer
```

I found that I needed to config.ini configuration, so I got the default configuration "release/config.ini.sample" in the 5.5.0 branch and modified it:

```
[default]
elasticsearch=https://user:pass@host:port
rotateIndex=daily

passwordSecret=ARKIME_PASSWORD
httpRealm=Moloch
interface=ARKIME_INTERFACE
pcapDir=ARKIME_INSTALL_DIR/raw
maxFileSizeG=12
tcpTimeout=600
tcpSaveTimeout=720
udpTimeout=30
icmpTimeout=10
maxStreams=1000000
maxPackets=10000
freeSpaceG=5%

rirFile=ARKIME_INSTALL_DIR/etc/ipv4-address-space.csv
ouiFile=ARKIME_INSTALL_DIR/etc/oui.txt

dropUser=nobody
dropGroup=daemon
parseSMTP=true
parseSMB=true
parseQSValue=false
supportSha256=false
maxReqBody=64

reqBodyOnlyUtf8=true

smtpIpHeaders=X-Originating-IP:;X-Barracuda-Apparent-Source-IP:

parsersDir=ARKIME_INSTALL_DIR/parsers
pluginsDir=ARKIME_INSTALL_DIR/plugins

spiDataMaxIndices=4

packetThreads=2
pcapWriteMethod=simple
pcapWriteSize=262143
maxESConns=30
maxESRequests=500
packetsPerPoll=50000

logEveryXPackets=100000
logUnknownProtocols=false
logESRequests=true
logFileCreation=true

[headers-http-request]
referer=type:string;count:true;unique:true
authorization=type:string;count:true
content-type=type:string;count:true
origin=type:string

[headers-http-response]
location=type:string
server=type:string
content-type=type:string;count:true

[headers-email]
x-priority=type:integer
authorization=type:string
```


The directory structure is as follows：
![img_v3_02gp_2417b08d-a5f8-4d16-a018-776918288a9g](https://github.com/user-attachments/assets/1f2d6a4f-6dfa-41b4-91ef-46ea695d4632)

Finally, used "docker-compose up -d" to create a container：
![img_v3_02gp_4d42749b-b360-4c2a-9058-03b744eb1d9g](https://github.com/user-attachments/assets/999b2721-cac1-4e5b-a912-193e465bba15)

---
capture's error message:
![img_v3_02gp_0e6301d7-81b3-4eaf-b5d2-932d33842a5g](https://github.com/user-attachments/assets/02c0823c-05c9-4330-be22-5cb0f0589d39)

viewer's error message:
![img_v3_02gp_6d0273c9-72f5-463a-8c7b-72a51afc270g](https://github.com/user-attachments/assets/8b90c881-9f04-4d5d-9896-7250a1e692f5)
---
@awick 
I've never built Arkime before, either binary or docker version, I thought initializing operations was automatic in docker versions, but apparently that's not the case. Is there a problem with my operation and what do I need to do next?
