### ISSUE TITLE
Docker Configuration ENV variables behavior different than documentation

### ISSUE THREAD

**Issue by stevesecurityoverview** [arkime/arkime#3085]
When starting the v5-latest image (5.6.1) of arkime capture, the environment variables of:

````
env:
- name: ARKIME_default__elasticsearch
   value: elasticsearch.local.foo
- name: ARKIME_default__prefix
   value: myprefix
````
(This being run in Kubernetes but, I believe it would apply to a Docker setup)
results in:

````
Jan 11 19:59:04 config.c:180 arkime_config_str(): prefix=
Jan 11 19:59:04 config.c:180 arkime_config_str(): elasticsearch=
````

Changing the variables to 
````
env:
- name: ARKIME__elasticsearch
   value: elasticsearch.local.foo
- name: ARKIME__prefix
   value: myprefix
````
results in the desired behavior:
````
Jan 11 20:02:25 config.c:180 arkime_config_str(): prefix=myprefix
Jan 11 20:02:25 config.c:180 arkime_config_str(): elasticsearch=https://elasticsearch.local.foo
````

Not sure if this is intended behavior, but definitely caused some headaches.
The [documentation](https://arkime.com/docker#ConfiguringArkimeContainers]) may be out of date or this may be unintended behavior.
To debug, I ran `/opt/arkime/bin/capture -c /path/to/config.ini`.  Now that it has been cleared I am using `/opt/arkime/bin/docker.sh capture --forever --update-geo`
